[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
# 指定源码包路径
packages = ["dcpam_cv"]

[project]
name = "dcpam"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=1.20.0",
    "matplotlib>=3.3.0",
    "scipy>=1.6.0",
    "rich>=13.0.0",
    "opencv-python>=4.13.0.90",
    "pydantic>=2.0.0",
]

[project.optional-dependencies]
camera = ["PyGObject>=3.50.0"]

[project.scripts]
dcpam = "dcpam_cv.cli:main"
